package tui

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/charmbracelet/bubbles/textarea"
	"github.com/charmbracelet/bubbles/textinput"
	"github.com/charmbracelet/bubbles/viewport"
	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"

	"github.com/Open-Makers/ai-coding-agents-orchestrator/internal/safefile"
)

var mdFileRe = regexp.MustCompile(`\S+\.md`)

// ArtifactViewerModel shows a workspace artifact file in a scrollable viewport.
// It appears automatically when a human gate fires so the user can review, edit,
// or request revisions from the planner before approving.
type ArtifactViewerModel struct {
	filename   string
	wsDir      string
	vp         viewport.Model
	width      int
	height     int
	ready      bool
	rawContent string // unwrapped content for re-wrapping on resize

	// revise is called with (artifactFilename, feedback) when the user submits
	// chat feedback. Nil when pipeline is unavailable.
	revise func(artifact, feedback string) error

	// Document navigation — browse between workspace artifacts.
	gateFilename string   // the original gate artifact that needs approval
	artifacts    []string // all .md files in wsDir, sorted
	artifactIdx  int      // index of current file in artifacts

	// chat mode — user types feedback, planner revises the artifact
	chatMode  bool
	chatInput textinput.Model
	chatBusy  bool
	chatErr   string

	// inline edit mode — embedded textarea replaces the viewport
	editMode bool
	editTA   textarea.Model
}

type artifactViewerClosedMsg struct {
	approved   bool
	regenerate bool
}
type artifactRevisionDoneMsg struct{ err error }
type artifactEditedMsg struct{ err error }

// newArtifactViewer opens wsDir/filename for review.
// revise may be nil when the pipeline is not yet available.
func newArtifactViewer(wsDir, hint string, w, h int, revise func(string, string) error) ArtifactViewerModel {
	filename := extractMDFilename(hint)

	var content string
	if filename != "" {
		data, err := safefile.ReadFile(wsDir, filename)
		if err != nil {
			content = fmt.Sprintf("File %q was not generated by the planner.\n\nPress Ctrl+A to approve and continue anyway, or Esc to close.", filename)
		} else {
			content = string(data)
		}
	} else {
		filename = "review"
		content = hint
	}

	ti := textinput.New()
	ti.Placeholder = "Describe changes you'd like…"
	ti.CharLimit = 0

	m := ArtifactViewerModel{
		filename:     filename,
		gateFilename: filename,
		wsDir:        wsDir,
		width:        w,
		height:       h,
		revise:       revise,
		chatInput:    ti,
	}
	m.artifacts, m.artifactIdx = discoverArtifacts(wsDir, filename)
	m.vp = viewport.New(w-4, m.vpHeight(false))
	m.rawContent = content
	m.vp.SetContent(wrapContent(content, w-6))
	m.ready = true
	return m
}

func extractMDFilename(hint string) string {
	return mdFileRe.FindString(hint)
}

func (m ArtifactViewerModel) Init() tea.Cmd { return nil }

func (m ArtifactViewerModel) Update(msg tea.Msg) (ArtifactViewerModel, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.WindowSizeMsg:
		m.width, m.height = msg.Width, msg.Height
		m.vp.Width = msg.Width - 4
		m.vp.Height = m.vpHeight(m.chatMode)
		m.rewrapContent()
		return m, nil

	case artifactRevisionDoneMsg:
		m.chatBusy = false
		if msg.err != nil {
			m.chatErr = msg.err.Error()
		} else {
			m.chatErr = ""
			m.chatMode = false
			m.chatInput.Blur()
			m.vp.Height = m.vpHeight(false)
			m.reloadContent()
		}
		return m, nil

	case artifactEditedMsg:
		if msg.err == nil {
			m.reloadContent()
		}
		return m, nil

	case tea.KeyMsg:
		// Inline edit mode: route keys to textarea.
		if m.editMode {
			switch msg.String() {
			case "esc":
				m.editMode = false
				m.editTA.Blur()
				return m, nil
			case "ctrl+s":
				content := m.editTA.Value()
				filePath := filepath.Join(m.wsDir, m.filename)
				err := os.WriteFile(filePath, []byte(content), 0o600)
				m.editMode = false
				m.editTA.Blur()
				if err == nil {
					m.reloadContent()
				}
				return m, func() tea.Msg { return artifactEditedMsg{err: err} }
			default:
				var cmd tea.Cmd
				m.editTA, cmd = m.editTA.Update(msg)
				return m, cmd
			}
		}

		// Chat mode: route keys to input or handle submit/cancel.
		if m.chatMode && !m.chatBusy {
			switch msg.String() {
			case "esc":
				m.chatMode = false
				m.chatInput.Blur()
				m.chatErr = ""
				m.vp.Height = m.vpHeight(false)
				return m, nil
			case "enter":
				feedback := strings.TrimSpace(m.chatInput.Value())
				if feedback == "" || m.revise == nil {
					return m, nil
				}
				m.chatBusy = true
				m.chatErr = ""
				m.chatInput.SetValue("")
				fn := m.revise
				artifact := m.filename
				return m, func() tea.Msg {
					return artifactRevisionDoneMsg{err: fn(artifact, feedback)}
				}
			default:
				var cmd tea.Cmd
				m.chatInput, cmd = m.chatInput.Update(msg)
				return m, cmd
			}
		}

		// Normal mode keys.
		switch msg.String() {
		case "ctrl+a":
			m.switchToGateArtifact()
			return m, func() tea.Msg { return artifactViewerClosedMsg{approved: true} }
		case "esc", "q":
			return m, func() tea.Msg { return artifactViewerClosedMsg{approved: false} }
		case "r":
			return m, func() tea.Msg { return artifactViewerClosedMsg{regenerate: true} }
		case "[", "left":
			if m.artifactIdx > 0 {
				m.switchToArtifact(m.artifactIdx - 1)
			}
		case "]", "right":
			if m.artifactIdx < len(m.artifacts)-1 {
				m.switchToArtifact(m.artifactIdx + 1)
			}
		case "e":
			if m.wsDir != "" && m.filename != "review" {
				data, err := safefile.ReadFile(m.wsDir, m.filename)
				if err != nil {
					return m, nil
				}
				ta := textarea.New()
				ta.SetValue(string(data))
				ta.Focus()
				ta.CharLimit = 0
				ta.SetWidth(m.width - 6)
				ta.SetHeight(m.vpHeight(false) - 1)
				m.editTA = ta
				m.editMode = true
				return m, textarea.Blink
			}
		case "c":
			if m.revise != nil {
				m.chatMode = true
				m.chatErr = ""
				m.chatInput.SetValue("")
				m.vp.Height = m.vpHeight(true)
				return m, m.chatInput.Focus()
			}
		case "up", "k":
			m.vp.ScrollUp(1)
		case "down", "j":
			m.vp.ScrollDown(1)
		case "pgup", "u":
			m.vp.HalfPageUp()
		case "pgdown", "d":
			m.vp.HalfPageDown()
		case "g":
			m.vp.GotoTop()
		case "G":
			m.vp.GotoBottom()
		}
		return m, nil
	}

	var cmd tea.Cmd
	m.vp, cmd = m.vp.Update(msg)
	return m, cmd
}

// vpHeight returns the viewport height given whether chat mode is active.
// Overhead: top border(1) + title row(1) + hints row(1) + bottom border(1) = 4,
// plus chat row(1) when active.
func (m ArtifactViewerModel) vpHeight(chatActive bool) int {
	overhead := 4
	if chatActive {
		overhead = 5
	}
	h := m.height - overhead
	if h < 2 {
		h = 2
	}
	return h
}

func (m *ArtifactViewerModel) reloadContent() {
	if m.wsDir == "" || m.filename == "review" {
		return
	}
	data, err := safefile.ReadFile(m.wsDir, m.filename)
	if err == nil {
		m.rawContent = string(data)
		m.vp.SetContent(wrapContent(m.rawContent, m.width-6))
		m.vp.GotoTop()
	}
}

// rewrapContent re-wraps the current raw content to the new width.
func (m *ArtifactViewerModel) rewrapContent() {
	if m.rawContent != "" {
		m.vp.SetContent(wrapContent(m.rawContent, m.width-6))
	}
}

// switchToArtifact loads the artifact at the given index.
func (m *ArtifactViewerModel) switchToArtifact(idx int) {
	if idx < 0 || idx >= len(m.artifacts) {
		return
	}
	m.artifactIdx = idx
	m.filename = m.artifacts[idx]
	m.reloadContent()
}

// switchToGateArtifact returns to the gate artifact before approval.
func (m *ArtifactViewerModel) switchToGateArtifact() {
	if m.filename == m.gateFilename {
		return
	}
	for i, name := range m.artifacts {
		if name == m.gateFilename {
			m.switchToArtifact(i)
			return
		}
	}
}

// discoverArtifacts lists .md files in wsDir sorted in pipeline order,
// returns the list and the index of the current filename.
func discoverArtifacts(wsDir, current string) ([]string, int) {
	// Pipeline order for known artifacts.
	ordered := []string{
		"requirements.md",
		"architecture.md",
		"implementation_plan.md",
		"prompts.md",
	}

	var result []string
	seen := make(map[string]bool)
	for _, name := range ordered {
		if _, err := os.Stat(filepath.Join(wsDir, name)); err == nil {
			result = append(result, name)
			seen[name] = true
		}
	}

	// Add any other .md files not in the predefined order.
	entries, err := os.ReadDir(wsDir)
	if err == nil {
		for _, e := range entries {
			if !e.IsDir() && strings.HasSuffix(e.Name(), ".md") && !seen[e.Name()] {
				result = append(result, e.Name())
			}
		}
	}

	// Ensure current file is in the list even if not on disk.
	idx := -1
	for i, name := range result {
		if name == current {
			idx = i
			break
		}
	}
	if idx == -1 && current != "" && current != "review" {
		result = append(result, current)
		idx = len(result) - 1
	}
	if idx == -1 {
		idx = 0
	}

	return result, idx
}

func (m ArtifactViewerModel) View() string {
	borderColor := roleColor("planner")
	bSt := lipgloss.NewStyle().Foreground(borderColor)
	titleStyle := lipgloss.NewStyle().Bold(true).Foreground(borderColor)
	dimStyle := lipgloss.NewStyle().Foreground(lipgloss.Color("240"))
	errStyle := lipgloss.NewStyle().Foreground(lipgloss.Color("160"))

	contentW := m.width - 2 // left border + right border
	if contentW < 2 {
		contentW = 2
	}

	// Title line inside the frame.
	pct := int(m.vp.ScrollPercent() * 100)
	scrollInfo := dimStyle.Render(fmt.Sprintf(" %d%%", pct))
	navInfo := ""
	if len(m.artifacts) > 1 {
		navInfo = dimStyle.Render(fmt.Sprintf("  [%d/%d]", m.artifactIdx+1, len(m.artifacts)))
	}
	gateMarker := ""
	if m.filename == m.gateFilename {
		gateMarker = titleStyle.Render(" ⏸")
	}
	titleLine := titleStyle.Render(m.filename) + gateMarker + navInfo + scrollInfo

	// Viewport or editor lines.
	var vpLines []string
	if m.editMode {
		vpLines = strings.Split(m.editTA.View(), "\n")
	} else {
		vpRaw := m.vp.View()
		vpLines = strings.Split(vpRaw, "\n")
	}
	targetH := m.vpHeight(m.chatMode)
	if len(vpLines) > targetH {
		vpLines = vpLines[:targetH]
	}
	for len(vpLines) < targetH {
		vpLines = append(vpLines, "")
	}
	innerW := contentW - 2 // 1 char padding each side
	_ = innerW

	// Hint line inside the frame.
	var hintLine string
	if m.editMode {
		hintLine = dimStyle.Render("Ctrl+S save   Esc cancel editing")
	} else if m.chatMode {
		if m.chatBusy {
			hintLine = dimStyle.Render("Revising… please wait")
		} else if m.chatErr != "" {
			hintLine = errStyle.Render("Error: "+m.chatErr) + "  " + dimStyle.Render("Esc cancel")
		} else {
			hintLine = dimStyle.Render("Feedback: ") + m.chatInput.View() + dimStyle.Render("  Enter submit   Esc cancel")
		}
	} else {
		var parts []string
		parts = append(parts, "↑↓/jk scroll")
		if len(m.artifacts) > 1 {
			parts = append(parts, "[/] prev/next")
		}
		if m.wsDir != "" && m.filename != "review" {
			parts = append(parts, "e edit")
		}
		if m.revise != nil {
			parts = append(parts, "c revise")
		}
		parts = append(parts, "r regenerate", "Ctrl+A approve", "Esc close")
		hintLine = dimStyle.Render(strings.Join(parts, "  "))
	}

	// Collect all interior rows: title, viewport lines, (optional chat), hints.
	interiorRows := make([]string, 0, targetH+3)
	interiorRows = append(interiorRows, titleLine)
	interiorRows = append(interiorRows, vpLines...)
	if m.chatMode {
		interiorRows = append(interiorRows, hintLine)
	} else {
		interiorRows = append(interiorRows, hintLine)
	}

	// Build bordered output.
	hRule := strings.Repeat("─", contentW)
	var sb strings.Builder
	sb.WriteString(bSt.Render("╭"+hRule+"╮") + "\n")
	for _, row := range interiorRows {
		vis := lipgloss.Width(row)
		pad := contentW - vis
		if pad < 0 {
			pad = 0
		}
		sb.WriteString(bSt.Render("│") + " " + row + strings.Repeat(" ", max(pad-1, 0)) + bSt.Render("│") + "\n")
	}
	sb.WriteString(bSt.Render("╰" + hRule + "╯"))

	return sb.String()
}

// truncateToWidth cuts a string to fit within maxW visible characters,
// appending "…" if truncated.
func truncateToWidth(s string, maxW int) string {
	if maxW <= 0 {
		return ""
	}
	runes := []rune(s)
	if lipgloss.Width(s) <= maxW {
		return s
	}
	for i := len(runes); i > 0; i-- {
		candidate := string(runes[:i]) + "…"
		if lipgloss.Width(candidate) <= maxW {
			return candidate
		}
	}
	return "…"
}

// wrapContent soft-wraps each line of text to maxW visible characters,
// breaking at word boundaries when possible.
func wrapContent(text string, maxW int) string {
	if maxW <= 0 {
		return text
	}
	lines := strings.Split(text, "\n")
	var result []string
	for _, line := range lines {
		result = append(result, wrapLine(line, maxW)...)
	}
	return strings.Join(result, "\n")
}

// wrapLine wraps a single line into multiple lines, each at most maxW
// visible characters wide, preferring breaks at spaces.
func wrapLine(line string, maxW int) []string {
	if lipgloss.Width(line) <= maxW {
		return []string{line}
	}

	words := strings.Fields(line)
	if len(words) == 0 {
		return []string{""}
	}

	// Detect leading whitespace to preserve indentation on continuation lines.
	indent := ""
	for _, r := range line {
		if r == ' ' || r == '\t' {
			indent += string(r)
		} else {
			break
		}
	}

	var wrapped []string
	current := indent + words[0]

	for _, word := range words[1:] {
		candidate := current + " " + word
		if lipgloss.Width(candidate) <= maxW {
			current = candidate
		} else {
			wrapped = append(wrapped, current)
			current = indent + "  " + word // continuation with extra indent
		}
	}
	wrapped = append(wrapped, current)
	return wrapped
}
